alter table CLIENTE_CONTRATO_CCUSTO drop constraint FKEC26B417E0AF29C;
alter table CLIENTE_CONTRATO_CCUSTO drop constraint FKEC26B41753DFD1DF;
alter table CLIENTE_CONTRATO_CCUSTO drop constraint FKEC26B41795493395;
alter table CLIENTE_CONTRATO_CCUSTO drop constraint FKEC26B4175C95BE75;
alter table CONTRATO_SERVICO_SLA drop constraint FK24B2F2C52085015;
alter table CONTRATO_SERVICO_SLA drop constraint FK24B2F2C558201D7D;
alter table CONTRATO_SERVICO_SLA drop constraint FK24B2F2C55C95BE75;
alter table CONTRATO_SERVICO_SLA drop constraint FK24B2F2C5C2D4A835;
alter table CONTRATO_VIGENCIA drop constraint FK4BAAC9A1C3606E4C;
alter table CONTRATO_VIGENCIA drop constraint FK4BAAC9A15C95BE75;
alter table DIA_SEMANA_INTERVALO drop constraint FK6F970087294F1DD;
alter table DIA_SEMANA_INTERVALO drop constraint FK6F970087B2BF4147;
alter table GRADE_HORAS_DIA drop constraint FKCF62AC32B2BF4147;
alter table GRADE_HORAS_DIA drop constraint FKCF62AC326AD409;
alter table TELEFONE drop constraint FKDD8E5AEA20D1A3DF;
alter table cep drop constraint FK1804E24CDCCA0;
alter table cidade drop constraint FKAEE65724A8F29C80;
alter table cliente drop constraint FK334B85FA24CDCCA0;
alter table cliente drop constraint FK334B85FAA8F29C80;
alter table consultor drop constraint FKE6E7BECFDA010FFF;
alter table contato drop constraint FK38B7262A53DFD1DF;
alter table contrato drop constraint FKDE35131C53DFD1DF;
alter table feriado drop constraint FKC68CBDB624CDCCA0;
alter table feriado drop constraint FKC68CBDB6A8F29C80;
alter table grade_intervalo drop constraint FKA08DCDE259DEBB01;
alter table grade_intervalo drop constraint FKA08DCDE26B5D73A1;
alter table other_grade_dia drop constraint FKD77795A5C3606E4C;
alter table permissao drop constraint FK284B8987C97043AB;
alter table usuario drop constraint FKF814F32EC97043AB;
drop table CENTRO_CUSTO cascade;
drop table CLIENTE_CONTRATO_CCUSTO cascade;
drop table CONTRATO_SERVICO_SLA cascade;
drop table CONTRATO_VIGENCIA cascade;
drop table DIA_SEMANA_INTERVALO cascade;
drop table GRADE_DIA cascade;
drop table GRADE_HORAS cascade;
drop table GRADE_HORAS_DIA cascade;
drop table INTERVALO_HORA cascade;
drop table PRAZO_ATENDIMENTO cascade;
drop table TELEFONE cascade;
drop table catalogo cascade;
drop table cep cascade;
drop table cidade cascade;
drop table cliente cascade;
drop table consultor cascade;
drop table contato cascade;
drop table contrato cascade;
drop table criatura cascade;
drop table feriado cascade;
drop table grade_categoria cascade;
drop table grade_horario cascade;
drop table grade_intervalo cascade;
drop table grupo_acesso cascade;
drop table logotipo cascade;
drop table other_grade_dia cascade;
drop table permissao cascade;
drop table pessoa cascade;
drop table prioridade cascade;
drop table uf cascade;
drop table usuario cascade;
drop sequence SEQ_CATALOGO;
drop sequence SEQ_CENTRO_CUSTO;
drop sequence SEQ_CEP;
drop sequence SEQ_CIDADE;
drop sequence SEQ_CLIENTE;
drop sequence SEQ_CLIENTE_CONTRATO_CCUSTO;
drop sequence SEQ_CONTRATO;
drop sequence SEQ_CONTRATO_SERVICO_SLA;
drop sequence SEQ_CONTRATO_VIGENCIA;
drop sequence SEQ_DIA_SEMANA_INTERVALO;
drop sequence SEQ_FERIADO;
drop sequence SEQ_GRADE_DIA;
drop sequence SEQ_GRADE_HORAS;
drop sequence SEQ_GRADE_HORAS_DIA;
drop sequence SEQ_GRUPO_ACESSO;
drop sequence SEQ_INTERVALO_HORA;
drop sequence SEQ_LOGOTIPO;
drop sequence SEQ_PERMISSAO;
drop sequence SEQ_PRAZO_ATENDIMENTO;
drop sequence SEQ_PRIORIDADE;
drop sequence SEQ_TELEFONE;
drop sequence SEQ_UF;
drop sequence SEQ_USUARIO;
drop sequence hibernate_sequence;
create table CENTRO_CUSTO (ID_CENTRO_CUSTO int8 not null, DS_CCUSTO varchar(255) not null, primary key (ID_CENTRO_CUSTO));
create table CLIENTE_CONTRATO_CCUSTO (ID_CLIENTE_CONTRATO_CCUSTO int8 not null, ccusto_id int8 not null, cliente_id int8 not null, contrato_id int8 not null, logotipo_id int8, primary key (ID_CLIENTE_CONTRATO_CCUSTO));
create table CONTRATO_SERVICO_SLA (ID_CONTRATO_SERVICO_SLA int8 not null, catalogo_id int8 not null, contrato_id int8 not null, DS_SERVICO varchar(255) not null, prazo_id int8 not null, prioridade_id int8 not null, QT_MINIMA_LANCAMENTO_MINUTOS int4 not null, primary key (ID_CONTRATO_SERVICO_SLA));
create table CONTRATO_VIGENCIA (ID_CONTRATO_VIGENCIA int8 not null, contrato_id int8 not null, DT_ASSINATURA_CONTRATO date not null, DT_INICIO_VIGENCIA date not null, DT_TERMINO_VIGENCIA date, grade_id int8, FL_CONTRATO_HORA_ABERTA bool not null, MG_SUP_FAT_EXTRA int4, NR_ADITIVO_CONTRATUAL int4, QT_HORAS_CONTRATADAS int4 not null, QT_TICKETS_CONTRATADOS int4, VL_CONTRATO numeric(19, 2) not null, primary key (ID_CONTRATO_VIGENCIA));
create table DIA_SEMANA_INTERVALO (ID_DIA_SEMANA_INTERVALO int8 not null, ID_GRADE_DIA int8 not null, ID_INTERVALO_HORA int8 not null, primary key (ID_DIA_SEMANA_INTERVALO));
create table GRADE_DIA (ID_GRADE_DIA int8 not null, DS_DIA_DA_SEMANA varchar(255) not null, FLAG_DIA_UTIL_NORMAL bool not null, primary key (ID_GRADE_DIA));
create table GRADE_HORAS (ID_GRADE_HORAS int8 not null, DS_GRADE_HORAS varchar(255) not null, primary key (ID_GRADE_HORAS));
create table GRADE_HORAS_DIA (ID_GRADE_HORAS_DIA int8 not null, ID_GRADE_HORAS int8 not null, ID_GRADE_DIA int8 not null, primary key (ID_GRADE_HORAS_DIA));
create table INTERVALO_HORA (ID_INTERVALO_HORA int8 not null, HORA_FIM time not null, HORA_INICIO time not null, PERCENTUAL_EXTRA float8 not null, primary key (ID_INTERVALO_HORA));
create table PRAZO_ATENDIMENTO (ID_PRAZO_ATENDIMENTO int8 not null, FL_PRAZO_INDETERMINADO bool not null, QT_MINUTOS_ATENDIMENTO int4 not null, primary key (ID_PRAZO_ATENDIMENTO));
create table TELEFONE (ID_TELEFONE int8 not null, contato_id int8 not null, NR_DDD int4, NR_TELEFONE int4 not null, DS_TIPO varchar(255) not null, fones_idx int4, primary key (ID_TELEFONE));
create table catalogo (ID_CATALOGO int8 not null, DS_CATALOGO varchar(255) not null, primary key (ID_CATALOGO));
create table cep (ID_CEP int8 not null, cidade_id int8 not null, CD_CEP int4 not null, DS_ENDERECO varchar(255) not null, primary key (ID_CEP));
create table cidade (ID_CIDADE int8 not null, CD_MUNICIPIO varchar(255) not null, DS_CIDADE varchar(255) not null, uf_id int8 not null, primary key (ID_CIDADE));
create table cliente (ID_CLIENTE int8 not null, FL_ATIVO bool not null, DS_BAIRRO varchar(20), COD_CEP int4, cidade_id int8 not null, CD_CNPJ_CORP int4 not null, CD_CNPJ_DIGITO int4 not null, CD_CNPJ_FILIAL int4, DS_ENDERECO_COMPLEMENTO varchar(20), DS_INSCR_ESTADUAL varchar(20), DS_INSCR_MUNICIPAL varchar(20), DS_ENDERECO varchar(20), DS_NOME_FANTASIA varchar(20) not null, NR_ENDERECO int4, DS_RAZAO_SOCIAL varchar(20) not null, uf_id int8 not null, primary key (ID_CLIENTE));
create table consultor (id int8 not null, usuario_id int8 not null, primary key (id));
create table contato (ID_CONTATO int8 not null, cliente_id int8, DS_DEPARTAMENTO varchar(255), primary key (ID_CONTATO));
create table contrato (ID_CONTRATO int8 not null, FL_ATIVO bool not null, cliente_id int8 not null, DT_INICIO_CONTRATO date not null, DS_CONTRATO varchar(255) not null, primary key (ID_CONTRATO));
create table criatura (id int8 not null, cpf int4 not null, digito int4 not null, primary key (id));
create table feriado (ID_FERIADO int8 not null, cidade_id int8, DT_FERIADO timestamp not null, FL_NACIONAL bool not null, uf_id int8, primary key (ID_FERIADO));
create table grade_categoria (id int8 not null, descricao varchar(255) not null, percentual int4 not null, primary key (id));
create table grade_horario (id int8 not null, descricao varchar(255) not null, primary key (id));
create table grade_intervalo (id int8 not null, categoria_id int8 not null, dia_id int8 not null, hora_fim int4 not null, hora_inicio int4 not null, primary key (id));
create table grupo_acesso (ID_GRUPO_ACESSO int8 not null, nome varchar(45) not null, primary key (ID_GRUPO_ACESSO));
create table logotipo (ID_LOGOTIPO int8 not null, DS_LOGOTIPO varchar(255) not null, primary key (ID_LOGOTIPO));
create table other_grade_dia (id int8 not null, dia varchar(255) not null, grade_id int8 not null, primary key (id));
create table permissao (ID_PERMISSAO int8 not null, CD_PERMISSAO varchar(30) not null, data_inclusao timestamp not null, grupo_id int8 not null, primary key (ID_PERMISSAO));
create table pessoa (ID_PESSOA int8 not null, DS_APELIDO varchar(25), CD_CPF int8, EMAIL varchar(255) not null, DS_NOME varchar(45) not null, CD_RG varchar(25), primary key (ID_PESSOA));
create table prioridade (ID_PRIORIDADE int8 not null, DS_PRIORIDADE varchar(255) not null, primary key (ID_PRIORIDADE));
create table uf (ID_UF int8 not null, CD_UF varchar(255) not null, DS_UF varchar(255) not null, primary key (ID_UF));
create table usuario (ID_USUARIO int8 not null, FL_ADMIN bool not null, grupo_id int8 not null, DS_NOME varchar(255) not null, DS_PASSWORD varchar(255) not null, primary key (ID_USUARIO));
alter table CLIENTE_CONTRATO_CCUSTO add constraint FKEC26B417E0AF29C foreign key (ccusto_id) references CENTRO_CUSTO;
alter table CLIENTE_CONTRATO_CCUSTO add constraint FKEC26B41753DFD1DF foreign key (cliente_id) references cliente;
alter table CLIENTE_CONTRATO_CCUSTO add constraint FKEC26B41795493395 foreign key (logotipo_id) references logotipo;
alter table CLIENTE_CONTRATO_CCUSTO add constraint FKEC26B4175C95BE75 foreign key (contrato_id) references contrato;
alter table CONTRATO_SERVICO_SLA add constraint FK24B2F2C52085015 foreign key (prioridade_id) references prioridade;
alter table CONTRATO_SERVICO_SLA add constraint FK24B2F2C558201D7D foreign key (prazo_id) references PRAZO_ATENDIMENTO;
alter table CONTRATO_SERVICO_SLA add constraint FK24B2F2C55C95BE75 foreign key (contrato_id) references contrato;
alter table CONTRATO_SERVICO_SLA add constraint FK24B2F2C5C2D4A835 foreign key (catalogo_id) references catalogo;
alter table CONTRATO_VIGENCIA add constraint FK4BAAC9A1C3606E4C foreign key (grade_id) references grade_horario;
alter table CONTRATO_VIGENCIA add constraint FK4BAAC9A15C95BE75 foreign key (contrato_id) references contrato;
alter table DIA_SEMANA_INTERVALO add constraint FK6F970087294F1DD foreign key (ID_INTERVALO_HORA) references INTERVALO_HORA;
alter table DIA_SEMANA_INTERVALO add constraint FK6F970087B2BF4147 foreign key (ID_GRADE_DIA) references GRADE_DIA;
alter table GRADE_HORAS_DIA add constraint FKCF62AC32B2BF4147 foreign key (ID_GRADE_DIA) references GRADE_DIA;
alter table GRADE_HORAS_DIA add constraint FKCF62AC326AD409 foreign key (ID_GRADE_HORAS) references GRADE_HORAS;
alter table TELEFONE add constraint FKDD8E5AEA20D1A3DF foreign key (contato_id) references contato;
alter table cep add constraint FK1804E24CDCCA0 foreign key (cidade_id) references cidade;
alter table cidade add constraint FKAEE65724A8F29C80 foreign key (uf_id) references uf;
alter table cliente add constraint FK334B85FA24CDCCA0 foreign key (cidade_id) references cidade;
alter table cliente add constraint FK334B85FAA8F29C80 foreign key (uf_id) references uf;
alter table consultor add constraint FKE6E7BECFDA010FFF foreign key (usuario_id) references usuario;
alter table contato add constraint FK38B7262A53DFD1DF foreign key (cliente_id) references cliente;
alter table contrato add constraint FKDE35131C53DFD1DF foreign key (cliente_id) references cliente;
alter table feriado add constraint FKC68CBDB624CDCCA0 foreign key (cidade_id) references cidade;
alter table feriado add constraint FKC68CBDB6A8F29C80 foreign key (uf_id) references uf;
alter table grade_intervalo add constraint FKA08DCDE259DEBB01 foreign key (categoria_id) references grade_categoria;
alter table grade_intervalo add constraint FKA08DCDE26B5D73A1 foreign key (dia_id) references other_grade_dia;
alter table other_grade_dia add constraint FKD77795A5C3606E4C foreign key (grade_id) references grade_horario;
alter table permissao add constraint FK284B8987C97043AB foreign key (grupo_id) references grupo_acesso;
alter table usuario add constraint FKF814F32EC97043AB foreign key (grupo_id) references grupo_acesso;
create sequence SEQ_CATALOGO;
create sequence SEQ_CENTRO_CUSTO;
create sequence SEQ_CEP;
create sequence SEQ_CIDADE;
create sequence SEQ_CLIENTE;
create sequence SEQ_CLIENTE_CONTRATO_CCUSTO;
create sequence SEQ_CONTRATO;
create sequence SEQ_CONTRATO_SERVICO_SLA;
create sequence SEQ_CONTRATO_VIGENCIA;
create sequence SEQ_DIA_SEMANA_INTERVALO;
create sequence SEQ_FERIADO;
create sequence SEQ_GRADE_DIA;
create sequence SEQ_GRADE_HORAS;
create sequence SEQ_GRADE_HORAS_DIA;
create sequence SEQ_GRUPO_ACESSO;
create sequence SEQ_INTERVALO_HORA;
create sequence SEQ_LOGOTIPO;
create sequence SEQ_PERMISSAO;
create sequence SEQ_PRAZO_ATENDIMENTO;
create sequence SEQ_PRIORIDADE;
create sequence SEQ_TELEFONE;
create sequence SEQ_UF;
create sequence SEQ_USUARIO;
create sequence hibernate_sequence;
